import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {MODES,ADVANCED_PATTERNS,createDictionary,generateProblem,seededRandom,allowedTermsFor,remainingHint} from '../js/generator.js';
import {Game,initialState,matches,isClear,validateStage,solveRemaining} from '../js/engine.js';
const d=createDictionary(JSON.parse(fs.readFileSync(new URL('../data/construction_terms_200.json',import.meta.url)))),fallbacks=JSON.parse(fs.readFileSync(new URL('../data/fallbacks.json',import.meta.url)));
test('上級A～Hは49文字、各モードの設定・辞書レベル・ヒントが正しい',()=>{assert.equal(ADVANCED_PATTERNS.length,8);for(const p of ADVANCED_PATTERNS)assert.equal(Object.entries(p).reduce((n,[k,v])=>n+Number(k)*v,0),49);for(const mode of MODES.filter(m=>m.gridSize===7)){assert.equal(mode.cellCount,49);assert.equal(mode.deadEndWarning,false);assert.equal(mode.hintEnabled,mode.id!=='advanced3');assert.deepEqual(mode.allowedLevels,['beginner1','beginner2','intermediate','advanced']);}});
test('上級各15問:初期成立なし・49文字・別セットと配置・実際の全消し証明',()=>{
 for(const mode of MODES.filter(m=>m.gridSize===7)){let previousHash=null,previousBoard=null;const patterns=new Set();let six=false;
  for(let i=0;i<15;i++){const s=generateProblem(mode.id,d,{rng:seededRandom(31000+i),previousHash,previousBoard,fallbacks});assert.equal(s.initialBoard.length,49);assert.equal(s.difficulty,'advanced');assert.equal(s.deadEndWarning,false);assert.equal(new Set(s.correctTerms).size,s.correctTerms.length);assert.notEqual(s.setHash,previousHash);assert.notEqual(JSON.stringify(s.initialBoard),previousBoard);assert.equal(matches(initialState(s),s,d).length,0);const lengths=s.correctTerms.map(id=>{assert.ok(mode.allowedLevels.includes(d[id].level));assert.ok(mode.allowedLengths.includes(d[id].length));return d[id].length;});six ||= lengths.includes(6);patterns.add(lengths.sort().join(''));validateStage(s,d);const g=new Game(s,d);for(const a of s.solutionRoute)assert.equal(g.move(a.from,a.to).blocked,false);assert.ok(isClear(g.state));while(g.undo()){}assert.deepEqual(g.state,initialState(s));g.reset();assert.deepEqual(g.state,initialState(s));previousHash=s.setHash;previousBoard=JSON.stringify(s.initialBoard);
  }assert.ok(patterns.size>=2);assert.equal(six,mode.id!=='advanced1');
 }
});
test('上級は手詰まりでも同時消去、履歴と空白を完全復元、6字最長優先',()=>{
 const words={long:{word:'品質管理基準'},mid:{word:'品質管理'},short:{word:'品質'},other:{word:'測量'}};
 for(const mode of MODES.filter(m=>m.gridSize===7)){const board=Array(49).fill(null);board[5]='品';board[48]='質';board[20]='管';board[22]='理';board[24]='基';board[26]='準';board[14]='測';board[15]='量';const stage={gridSize:7,difficulty:'advanced',deadEndWarning:mode.deadEndWarning,solverScope:'dictionary',correctTerms:['long','other'],initialBoard:board,allowedTerms:allowedTermsFor(board,words,7)};const g=new Game(stage,words),before=structuredClone(g.state),r=g.move(48,6);assert.equal(r.blocked,false);assert.equal(r.cleared.length,2);assert.equal(solveRemaining(g.state,stage,words),null);g.undo();assert.deepEqual(g.state,before);g.move(48,47);assert.equal(g.state.board[48],null);g.undo();assert.deepEqual(g.state,before);
 }
 const board=Array(49).fill(null);Array.from(words.long.word).slice(0,5).forEach((c,i)=>board[i]=c);board[48]='準';const stage={gridSize:7,difficulty:'advanced',initialBoard:board,allowedTerms:allowedTermsFor(board,words,7)};const g=new Game(stage,words);assert.deepEqual(g.move(48,5).cleared.map(m=>m.termId),['long']);assert.ok(isClear(g.state));
});
test('上級予備問題とヒントは選択語を保持、全ルートと生成失敗時も検証',()=>{for(const mode of MODES.filter(m=>m.gridSize===7)){const s=generateProblem(mode.id,d,{maxSets:0,fallbacks});assert.equal(s.fallback,true);validateStage(s,d);const g=new Game(s,d);const hint=remainingHint(g.state,s,d,()=>0);assert.ok(s.correctTerms.some(id=>d[id].word===hint));const other=generateProblem(mode.id,d,{maxSets:0,fallbacks,previousHash:s.setHash});assert.notEqual(other.setHash,s.setHash);}});
