import {chromium} from 'playwright';import fs from 'node:fs';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';import {Game,matches,initialState} from '../js/engine.js';import {createDictionary,allowedTermsFor,MODES} from '../js/generator.js';
const dictionary=createDictionary(JSON.parse(fs.readFileSync(new URL('../data/construction_terms_200.json',import.meta.url)))),fixtures=JSON.parse(fs.readFileSync(new URL('../data/fallbacks.json',import.meta.url)));
const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'chrome'}),errors=[];
const board=p=>p.locator('.tile span').allTextContents();
const waitBoard=(p,expected)=>p.waitForFunction(expected=>document.querySelectorAll('.tile span').length===expected.length&&document.querySelector('#board').getAttribute('aria-busy')==='false'&&Array.from(document.querySelectorAll('.tile span')).every((el,i)=>el.textContent===(expected[i]||'')),expected);
async function press(p,selector,mobile=false){if(mobile)await p.locator(selector).tap();else await p.locator(selector).click();}
async function move(p,from,to,mobile=false){const a=p.locator(`.tile[data-index="${from}"]`),b=p.locator(`.tile[data-index="${to}"]`);if(mobile){await a.tap();await p.waitForFunction(i=>document.querySelector(`.tile[data-index="${i}"]`).getAttribute('aria-pressed')==='true',from);await b.tap();}else{await a.click();await b.click();}}
async function prepare(mobile=false,stub=true){const context=await browser.newContext(mobile?{viewport:{width:390,height:844},isMobile:true,hasTouch:true}:{viewport:{width:1280,height:1000}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));if(stub)await page.route('**/js/generation-worker.js',route=>route.fulfill({contentType:'text/javascript',body:`const fixtures=${JSON.stringify(fixtures)};self.onmessage=({data})=>self.postMessage({stage:fixtures.find(s=>s.id===data.mode&&s.setHash!==data.options.previousHash)});`}));await page.goto('http://localhost:4173');await page.locator('.stage-button').last().waitFor();return {context,page};}
async function play(p,s,mobile){const game=new Game(s,dictionary);let observed=false;for(const a of s.solutionRoute){const before=structuredClone(game.state);await move(p,a.from,a.to,mobile);const r=game.move(a.from,a.to);if(r.cleared.length&&!observed){await p.waitForFunction(()=>document.querySelector('#board').getAttribute('aria-busy')==='true');assert.ok(await p.locator('.clearing').count()>0);assert.equal(await p.locator('#new-problem').isDisabled(),true);assert.equal(await p.locator('#hint').isDisabled(),true);assert.equal(await p.locator('#undo').isDisabled(),true);observed=true;}await waitBoard(p,game.state.board);if(r.cleared.length&&observed===true){observed='done';await press(p,'#undo',mobile);assert.deepEqual(await board(p),before.board.map(c=>c||''));await move(p,a.from,a.to,mobile);await waitBoard(p,game.state.board);}}
 assert.equal(await p.locator('#clear-screen').isVisible(),true);assert.deepEqual(await p.locator('.learned-word h3').allTextContents(),s.correctTerms.map(id=>dictionary[id].word));}
function blockedMove(s){for(let from=0;from<s.initialBoard.length;from++)for(let to=from+1;to<s.initialBoard.length;to++){const g=new Game(s,dictionary);if(g.move(from,to).blocked)return {from,to};}return null;}
try{
 // Exercise actual Worker generation first, without test fixtures.
 const real=await prepare(false,false),rp=real.page;await press(rp,'.stage-button:first-child');await rp.locator('#play-screen').waitFor({state:'visible'});const first=await board(rp);assert.equal(first.filter(Boolean).length,25);assert.equal(matches({board:first,used:{}},{gridSize:5,allowedTerms:allowedTermsFor(first,dictionary)},dictionary).length,0);await rp.locator('#hint').click();assert.match(await rp.locator('#hint-message').textContent(),/ヒント：/);await rp.locator('#new-problem').click();await rp.waitForFunction(old=>document.querySelectorAll('.tile span').length===25&&document.querySelector('#board').getAttribute('aria-busy')==='false'&&Array.from(document.querySelectorAll('.tile span')).map(el=>el.textContent).join('')!==old,first.join(''));console.log('PASS: 実Workerのランダム生成・再生成・ヒント');await real.context.close();
 for(const mobile of (process.env.MOBILE_ONLY?[true]:[false,true])){const {page:p}=await prepare(mobile);await p.screenshot({path:fileURLToPath(new URL(`../screenshots/selection${mobile?'-mobile':''}.png`,import.meta.url))});
  for(let i=process.env.ADVANCED_ONLY?6:0;i<MODES.length;i++){const mode=MODES[i].id,s=fixtures.find(s=>s.id===mode);await press(p,`.stage-button:nth-child(${i+1})`,mobile);await waitBoard(p,s.initialBoard);assert.equal(await p.locator('#hint').isVisible(),MODES[i].hint);assert.equal(await p.locator('#learned').isVisible(),false);
   if(i<2){await press(p,'#hint',mobile);const text=await p.locator('#hint-message').textContent();assert.ok(s.correctTerms.some(id=>text.includes(dictionary[id].word)));assert.ok(!/行|列/.test(text));}
   const warning=blockedMove(s);if(warning){await move(p,warning.from,warning.to,mobile);await p.locator('#dead-end-warning').waitFor({state:'visible'});assert.deepEqual(await board(p),s.initialBoard);await press(p,'#dead-end-warning button',mobile);}
   if(i===0||i===3||i===6){const a=s.solutionRoute[0],b0=await p.locator(`.tile[data-index="${a.from}"]`).boundingBox(),b1=await p.locator(`.tile[data-index="${a.to}"]`).boundingBox(),start={x:b0.x+b0.width/2,y:b0.y+b0.height/2},end={x:b1.x+b1.width/2,y:b1.y+b1.height/2};
    if(mobile){const cdp=await p.context().newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...start,id:1}]});for(let n=1;n<=8;n++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+(end.x-start.x)*n/8,y:start.y+(end.y-start.y)*n/8,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{await p.mouse.move(start.x,start.y);await p.mouse.down();await p.mouse.move(end.x,end.y,{steps:8});await p.mouse.up();}
    const g=new Game(s,dictionary);g.move(a.from,a.to);await waitBoard(p,g.state.board);await press(p,'#reset',mobile);assert.deepEqual(await board(p),s.initialBoard);}
   const tile=await p.locator('.tile').first().boundingBox();assert.ok(Math.abs(tile.width-tile.height)<2);assert.ok(tile.width>=(i>=6?38:44));if(mobile){assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:fileURLToPath(new URL('../screenshots/mobile.png',import.meta.url))});}
   await play(p,s,mobile);const next=fixtures.find(f=>f.id===mode&&f.setHash!==s.setHash);await press(p,'#replay',mobile);await waitBoard(p,next.initialBoard);assert.notDeepEqual(await board(p),s.initialBoard);await press(p,'#reset',mobile);assert.deepEqual(await board(p),next.initialBoard);await press(p,'#back-to-selection',mobile);
  }console.log(`PASS: ${mobile?'スマホ':'PC'}9モード、正方形マス、ドラッグ、警告、ヒント、全消し、戻す、同一リセット、新問題`);
 }
 // Force Worker creation failure and verify usable, certified fallback.
 const fail=await prepare();await fail.page.addInitScript(()=>{window.Worker=class{constructor(){throw new Error('test worker unavailable');}};});await fail.page.reload();await fail.page.locator('.stage-button').last().waitFor();await fail.page.locator('.stage-button').first().click();await waitBoard(fail.page,fixtures[0].initialBoard);console.log('PASS: Worker失敗時の予備問題');
 assert.deepEqual(errors,[]);
}catch(error){console.error(error);process.exitCode=1;throw error;}finally{const shutdown=setTimeout(()=>process.exit(process.exitCode||0),5000);await browser.close();clearTimeout(shutdown);}


