import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Game,initialState,resolveSwap,matches,isClear,validateStage,canSelectStage} from '../js/engine.js';
const dictionary=JSON.parse(fs.readFileSync(new URL('../data/terms.json',import.meta.url))),{stages}=JSON.parse(fs.readFileSync(new URL('../data/stages.json',import.meta.url)));
const boards=['督圧丁測基転平監削量掛来筋水形張器矢掘配図準点出員','水床点土測筋工面型生準枠切施鉄点路盛養路足法盤土場','量径舗杭養面厚出盤枠路筋来法工装足施測型高鉄場図生'];
const blank=()=>({board:Array(25).fill(null),used:{},completed:[]});
function trial(stage,id){const g=new Game(stage,dictionary),word=Array.from(dictionary[id].word);for(const [to,c]of [[3,word[0]],[24,word[1]]]){const from=g.state.board.indexOf(c);[g.state.board[from],g.state.board[to]]=[g.state.board[to],g.state.board[from]];}return g;}
test('指定の初級3盤面と正解文字数・漢字個数が完全一致',()=>{assert.equal(stages.length,3);for(const [i,s]of stages.entries()){assert.deepEqual(s.initialBoard,Array.from(boards[i]));assert.deepEqual([...s.initialBoard].sort(),s.correctTerms.flatMap(id=>Array.from(dictionary[id].word)).sort());assert.equal(s.initialBoard.length,25);assert.equal(s.terms.length,s.correctTerms.length);assert.ok(s.terms.every(t=>t.term===dictionary[t.termId].word&&t.description));const g=new Game(s,dictionary);assert.deepEqual(g.state.completed,[]);assert.equal(g.history.length,0);}});
test('3ステージ全正解ルートで全消し、全履歴を戻すと初期状態',()=>{for(const s of stages){assert.equal(validateStage(s,dictionary),true);const g=new Game(s,dictionary),initial=structuredClone(g.state);for(const a of s.solutionRoute){const r=g.move(a.from,a.to);assert.equal(r.changed,true);assert.equal(r.blocked,false);}assert.equal(isClear(g.state),true);assert.deepEqual(new Set(g.state.completed),new Set(s.correctTerms));assert.equal(g.history.length,s.solutionRoute.length);while(g.history.length)g.undo();assert.deepEqual(g.state,initial);}});
test('初級2の路・点・土はそれぞれ2個、重複文字の交換・復元',()=>{const s=stages[1];for(const c of ['路','点','土'])assert.equal(s.initialBoard.filter(x=>x===c).length,2);const g=new Game(s,dictionary),initial=structuredClone(g.state);assert.equal(g.move(16,19).changed,false);const a=s.solutionRoute[0];g.move(a.from,a.to);g.undo();assert.deepEqual(g.state,initial);});
test('全警告対象語の消去は残り文字を検証して拒否し、全状態を保持',()=>{for(const s of stages)for(const id of s.warningTerms){const g=trial(s,id),before=structuredClone(g.state),r=g.move(24,4);assert.equal(r.blocked,true,`${s.name}: ${id}`);assert.equal(r.changed,false);assert.deepEqual(g.state,before);assert.equal(g.history.length,0);}});
test('初級2の測点は警告対象でなく正解として安全に消去',()=>{const s=stages[1],g=new Game(s,dictionary);for(const a of s.solutionRoute)g.move(a.from,a.to);assert.equal(g.state.used.surveyPoint,1);assert.equal(isClear(g.state),true);});
test('水平器・基準点・監督員・配筋図・測量杭・鉄筋径・舗装厚・施工図の長語優先',()=>{for(const [long,short]of [['level','horizontal'],['reference','standard'],['supervisor','supervision'],['reinforcement','rebar'],['surveyStake','survey'],['rebarDiameter','steel'],['pavementThickness','pavement'],['constructionDrawing','construction']])for(const cells of [[0,1,2],[0,5,10]]){const s=blank(),word=Array.from(dictionary[long].word);s.board[cells[0]]=word[0];s.board[cells[1]]=word[1];s.board[24]=word[2];const r=resolveSwap(s,{allowedTerms:[{termId:short,maxUses:1},{termId:long,maxUses:1}]},dictionary,24,cells[2]);assert.deepEqual(r.state.completed,[long]);assert.equal(isClear(r.state),true);}});
test('逆順・斜め・行またぎ・非連続は不成立',()=>{for(const cells of [[1,0],[5,0],[4,5],[0,6],[0,2]]){const s=blank();cells.forEach((i,n)=>s.board[i]=['丁','張'][n]);assert.equal(matches(s,stages[0],dictionary).length,0);}});
test('複数用語の同時成立・共有マスを正しく記録し一度消す',()=>{const s=blank();s.board.splice(0,4,'丁','張','掛','矢');s.board[10]='転';s.board[24]='圧';assert.equal(resolveSwap(s,stages[0],dictionary,24,11).cleared.length,3);const t=blank();t.board.splice(5,3,'基','準','点');t.board[24]='測';const r=resolveSwap(t,stages[0],dictionary,24,2);assert.deepEqual(new Set(r.state.completed),new Set(['reference','surveyPoint']));assert.equal(isClear(r.state),true);});
test('交換・消去・空白移動を1操作ずつ完全復元',()=>{const g=new Game(stages[0],dictionary);g.state=blank();g.state.board[0]='丁';g.state.board[24]='張';const before=structuredClone(g.state);g.move(24,1);assert.equal(g.history.length,1);assert.equal(isClear(g.state),true);g.undo();assert.deepEqual(g.state,before);g.move(24,12);assert.equal(g.state.board[24],null);g.undo();assert.deepEqual(g.state,before);});
test('拒否操作は既存の履歴を消費・追加しない',()=>{const g=trial(stages[0],'horizontal');g.history=[initialState(stages[0])];const before=structuredClone(g.state),history=structuredClone(g.history);for(let n=0;n<2;n++){assert.equal(g.move(24,4).blocked,true);assert.deepEqual(g.state,before);assert.deepEqual(g.history,history);}g.undo();assert.deepEqual(g.state,initialState(stages[0]));});
test('最初からで各ステージの全状態を初期化',()=>{for(const s of stages){const g=new Game(s,dictionary);for(const a of s.solutionRoute)g.move(a.from,a.to);g.reset();assert.deepEqual(g.state,initialState(s));assert.equal(g.history.length,0);assert.equal(g.undo(),false);}});
test('中級・上級設定では警告なく消去し、手動で戻せる',()=>{for(const difficulty of ['intermediate','advanced'])for(const s of stages){const g=trial({...s,difficulty},s.warningTerms[0]),before=structuredClone(g.state),r=g.move(24,4);assert.equal(r.blocked,false);assert.equal(g.state.board.filter(Boolean).length<25,true);g.undo();assert.deepEqual(g.state,before);}});
test('全開放・順次開放の切替をデータ設定で行える',()=>{const completed=new Set();assert.equal(canSelectStage(stages,2,completed,'all'),true);assert.equal(canSelectStage(stages,1,completed,'sequential'),false);assert.equal(canSelectStage(stages,0,completed,'sequential'),true);completed.add(stages[0].id);assert.equal(canSelectStage(stages,1,completed,'sequential'),true);assert.equal(canSelectStage(stages,2,completed,'sequential'),false);assert.equal(canSelectStage(stages,3,completed),false);});
test('不正な問題・正解語・ルート・難易度を検出',()=>{for(const mutate of [s=>s.initialBoard.pop(),s=>s.initialBoard[0]='猫',s=>s.allowedTerms[0].maxUses=0,s=>s.correctTerms=['unknown'],s=>s.solutionRoute=[],s=>s.solutionRoute.pop(),s=>s.solutionRoute[0].from=-1,s=>s.difficulty='invalid']){const s=structuredClone(stages[0]);mutate(s);assert.throws(()=>validateStage(s,dictionary));}});

