import {test} from 'node:test';import assert from 'node:assert/strict';import {Game,resolveSwap,initialState} from '../js/engine.js';
const dictionary={quality:{word:'品質'},qualityManagement:{word:'品質管理'},qualityStandard:{word:'品質管理基準'},survey:{word:'測量'},stake:{word:'測量杭'},construction:{word:'施工'},management:{word:'施工管理'},rebar:{word:'配筋'},drawing:{word:'配筋図'},mallet:{word:'掛矢'}};
function stage(long,n){return {gridSize:n,difficulty:({5:'beginner',6:'intermediate',7:'advanced'})[n],deadEndWarning:false,correctTerms:[long],initialBoard:Array(n*n).fill(null),allowedTerms:Object.keys(dictionary).map(termId=>({termId,maxUses:2}))};}
test('全難易度・縦横:品質と品質管理、測量、施工、配筋を保留し長語は全消去',()=>{
 for(const n of [5,6,7])for(const step of [1,n])for(const [long,short]of [['stake','survey'],['management','construction'],['drawing','rebar'],...(n>=6?[['qualityStandard','quality'],['qualityStandard','qualityManagement']]:[])]){const s=stage(long,n),letters=Array.from(dictionary[long].word),prefix=Array.from(dictionary[short].word);letters.forEach((c,i)=>s.initialBoard[n*n-1-i]=c);const g=new Game(s,dictionary),before=structuredClone(g.state);for(let i=0;i<prefix.length;i++){const from=g.state.board.findIndex((c,j)=>c===letters[i]&&j!==i*step);const r=g.move(from,i*step);assert.equal(r.cleared.length,0);assert.equal(r.blocked,false);}assert.equal(g.state.board[0],letters[0]);assert.deepEqual(g.state.completed,[]);for(let i=prefix.length;i<letters.length;i++){if(g.state.used[long])break;if(g.state.board[i*step]===letters[i])continue;const from=g.state.board.findIndex((c,j)=>c===letters[i]&&j!==i*step);g.move(from,i*step);}assert.deepEqual(g.state.completed,[long]);assert.ok(g.state.board.every(c=>c===null));while(g.undo()){}assert.deepEqual(g.state,before);}
});
test('別位置の同じ短語と無関係な短語は消去し、組み立て位置だけ保留',()=>{
 const s=stage('stake',7);s.initialBoard[0]='測';s.initialBoard[1]='量';s.initialBoard[10]='測';s.initialBoard[48]='量';s.initialBoard[25]='杭';s.initialBoard[35]='掛';s.initialBoard[36]='矢';const g=new Game(s,dictionary),r=g.move(48,11);assert.deepEqual(new Set(r.cleared.map(m=>m.termId)),new Set(['survey','mallet']));assert.equal(g.state.board[0],'測');assert.equal(g.state.board[1],'量');assert.equal(g.state.board[10],null);g.undo();assert.deepEqual(g.state,initialState(s));
});
test('長語消去済み・盤端で延長不可・必要な文字不足なら短語を通常消去',()=>{for(const variant of ['used','edge','missing']){const s=stage('stake',7);const start=variant==='edge'?5:0;s.initialBoard[start]='測';s.initialBoard[48]='量';if(variant!=='missing')s.initialBoard[25]='杭';const state=initialState(s);if(variant==='used')state.used.stake=1;const r=resolveSwap(state,s,dictionary,48,start+1);assert.ok(r.cleared.some(m=>m.termId==='survey'));}});
